run:
	mpirun -np 8 ~/WInc3D/incompact3d Smag1.in

vis:
	~/WInc3D/visualize Smag1.pprc

clean:
	rm -rf *.dat ux* uy* uz* pp* vort* qcrit* Temp* IBM* Ftx* Fty* Ftz* gammadisc* nuSGS* probe* ALM ADM *.xdmf
