#!/usr/bin/env python
"""
Python script that reads from the probe file
"""
import numpy as np
from scipy.signal import welch
import matplotlib.pyplot as plt
import argparse
from math import pi


def autocorr(x):
    result = np.correlate(x, x, mode='full')
    return result[result.size // 2:]

# ====================================
# Parser Arguments
# ====================================
parser = argparse.ArgumentParser(description="Script to read from the velocity probes probe******.dat files")
parser.add_argument("-v","--verbose",action="store_true",help="Print location")
parser.add_argument("-p","--plot",action="store_true",help="Plots the wake profiles")
parser.add_argument("-w","--write",action="store_true",help="Write results in a .csv file")
parser.add_argument("PATH", type=str, help="path to where the umean, vmean etc. files are (should end with a / )")
parser.add_argument("SPINUPSTEPS", type=int, help="Number of time step until spinup time")
parser.add_argument("SAMPLINGSTEPS", type=int, help="Number of sampling steps after spinup time")
parser.add_argument("SAMPLINGPERIOD", type=float, help="Period of sampling")
parser.add_argument("PROBES", type=int, help="Number of probe points")
parser.add_argument("OUTPUT", type=str, help="OUTPUT FOLDER")

args = parser.parse_args()
path = args.PATH
T=args.SPINUPSTEPS
M=args.SAMPLINGSTEPS
Time=args.SAMPLINGPERIOD
N = args.PROBES
output = args.OUTPUT

X=np.zeros((M,N,4));
Y=np.zeros((M,N,4));
Z=np.zeros((M,N,4));

U=np.zeros((M,N,4));
V=np.zeros((M,N,4));
W=np.zeros((M,N,4));

Nhalf=int(N/2)
print(Nhalf)
H=1000;
ustar=0.45;
Uinf=ustar/0.4*np.log(1000/0.1)
for i in range(M):
    probeNumber=T+i+1
    A=np.genfromtxt(path+'probe'+str(probeNumber).zfill(6),skip_header=1,delimiter=',')
    for j in range(N):
        for k in range(4):	
            X[i,j,k]=A[k*N+j,1];
            Y[i,j,k]=A[k*N+j,2];
            Z[i,j,k]=A[k*N+j,3];
            U[i,j,k]=A[k*N+j,4];
            V[i,j,k]=A[k*N+j,5];
            W[i,j,k]=A[k*N+j,6];

Uave1=np.average(U[:,Nhalf,0])
Uave2=np.average(U[:,Nhalf,1])
Uave3=np.average(U[:,Nhalf,2])
Uave4=np.average(U[:,Nhalf,3])

#plt.figure(1)
#plt.plot(U[:,Nhalf,0]-Uave1,label='y/H='+str(Y[0,Nhalf,0]/H))
#plt.plot(U[:,Nhalf,1]-Uave2,label='y/H='+str(Y[0,Nhalf,1]/H))
##plt.plot(U[:,Nhalf,2]-Uave3,label='y/H='+str(Y[0,Nhalf,2]/H))
##plt.plot(U[:,Nhalf,3]-Uave4,label='y/H='+str(Y[0,Nhalf,3]/H))
#plt.legend()
#plt.show()

R1=0;R2=0;R3=0;R4=0

sigma1sq=np.sum((U[:,Nhalf,0]-Uave1)**2.)/(M-1)
sigma2sq=np.sum((U[:,Nhalf,1]-Uave2)**2.)/(M-1)
sigma3sq=np.sum((U[:,Nhalf,2]-Uave3)**2.)/(M-1)
sigma4sq=np.sum((U[:,Nhalf,3]-Uave4)**2.)/(M-1)

print(Uave1,Uave2,Uave3,Uave4)
print(sigma1sq,sigma2sq,sigma3sq,sigma4sq)

r1=autocorr(U[:,Nhalf,0]-Uave1)
r2=autocorr(U[:,Nhalf,1]-Uave2)
r3=autocorr(U[:,Nhalf,2]-Uave3)
r4=autocorr(U[:,Nhalf,3]-Uave4)

#plt.figure(2)
#plt.plot(r1)
#plt.show()

T1=0;T2=0;T3=0;T4=0;
for i in range(len(r1)):
	if(r1[i]<0.):
		break;	
	else:
		T1=T1+r1[i]/r1[0]*Time

for i in range(len(r2)):
	if(r2[i]<0.):
		break;	
	else:
		T2=T2+r2[i]/r2[0]*Time

for i in range(len(r3)):
	if(r3[i]<0.05):
		break;	
	else:
		T3=T3+r3[i]/r3[0]*Time

for i in range(len(r4)):
	if(r4[i]<0.05):
		break;	
	else:
		T4=T4+r4[i]/r4[0]*Time

L1=Uave1*T1
L2=Uave2*T2
L3=Uave3*T3
L4=Uave4*T4

Distance=[Y[0,Nhalf,0]/H,Y[0,Nhalf,1]/H,Y[0,Nhalf,2]/H,Y[0,Nhalf,3]/H]
LengthScale=[L1/H,L2/H,L3/H,L4/H]
TimeScale=[T1/H*Uinf,T2/H*Uinf,T3/H*Uinf,T4/H*Uinf]

print(Distance)
print(LengthScale)
print(TimeScale)
	
if args.write:     
    with open(output+'IntegralScales.dat','w') as fout:
        fout.write('# y/H L/H T/(H/Uinf) \n')
        for i in range(len(Distance)):
            fout.write(str(Distance[i])+' '+str(float(LengthScale[i]))+' '+str(float(TimeScale[i]))+'\n')

