run:
	mpirun -np 1 ~/WInc3D/incompact3d NREL-5MW.in

vis:
	~/WInc3D/visualize NREL-5MW.pprc

clean:
	rm -rf *.dat *.load *.perf ux* uy* uz* pp* vort* qcrit* temp* Ftx* Fty* Ftz* nuSGS* probe* ALM *.xdmf
